### ISSUE TITLE
Subathon leaderboards? Most active chatter, most subs, most bits, most active while sleeping etc

### ISSUE THREAD

**Issue by Mahcks** [Esfands/RetPaladinBot3#9]
I could add these features to RetPaladinBot. Then I can add endpoints to its API which we can use for an overlay or just add it to Onlyfands/another site maybe?

For most active, is it the chatters that are there the most or ones that send the most messages?

**Comment by Sdyess** [comment]
These features are definitely best for the bot. Overall I'd like to see if we can record general stats on the stream throughout the subathon for like an end report and could probably do an overlay & onlyfands for display honestly. One for esfand if he wants to show on stream at some point or during the nights, and then one that people can consistently check if they wanted.

We'll have to work out some way to make the active chatter boards not incentivize spamming chat. Twitch already kinda does though so might not be a big concern. Hard to tell who is actually there bc of Chatterino though

**Comment by Mahcks** [comment]
Added event logging for RPB for keeping track of message count, gifted subs, and bits donated.

Endpoints
- https://api.retpaladinbot.com/subathon/chatters
- https://api.retpaladinbot.com/subathon/giftedsubs
- https://api.retpaladinbot.com/subathon/bitsdonated

Maybe we make an arbitrary scoring system, like a mix of sent messages and time spent in chat? Or just messages sent and disguise it for when chat sees it.

**Comment by Sdyess** [comment]
Do these endpoints have pagination/offset/cursors?

**Comment by Mahcks** [comment]
N ![omagelul](https://cdn.frankerfacez.com/emote/128054/1) I'll work on adding offset to each with a limit of a 100 maybe?

**Comment by acdvs** [comment]
Usually with endpoints that return a lot of data, you split it into pages of a default size (so 100 would be a good starting point) and then have an optional parameter that lets you change that size.

**Comment by Mahcks** [comment]
On it 👍

**Comment by Mahcks** [comment]
Added `offset` and `limit` to the subathon endpoints. By default it's 100, I put a bunch of fake data in it.
`https://api.retpaladinbot.com/subathon/chatters?offset=1&limit=100`

**Comment by Mahcks** [comment]
Bot, database and API are good to go for the subathon. 👍
